name: example
description: Example for illuminare
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1'

dependencies:
  flutter:
    sdk: flutter
  illuminare:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: